$ErrorActionPreference = "Stop"
Set-Location -Path $PSScriptRoot

# Reverse of install.ps1 (Windows). Removes the artefacts install.ps1 creates:
# the ~\.evomas-venv, the `evomas` function in your $PROFILE, the 'evomas'
# Jupyter kernel, and app\node_modules. Your data is left alone by default --
# pass --purge to ALSO delete the SWE-bench clone and the .env files (which
# hold your API keys). Idempotent: safe to re-run, no-ops on anything gone.

$RepoRoot = $PSScriptRoot
# Same path install.ps1 / start_api.ps1 / run_tests.py use.
$VenvDir      = Join-Path $HOME ".evomas-venv"
$PythonEvomas = Join-Path $VenvDir "Scripts\python.exe"

# Markers install.ps1 wraps its profile function in (kept in sync).
$Marker    = "# >>> evomas-cli >>>"
$EndMarker = "# <<< evomas-cli <<<"

# Delete a directory tree, returning $true/$false instead of throwing so a
# locked file (e.g. python.exe held by a live process) doesn't abort the whole
# uninstall. Retries once after clearing read-only attributes that can block
# deletion.
function Remove-Tree {
    param([Parameter(Mandatory)][string]$Path)
    if (-not (Test-Path $Path)) { return $true }
    try {
        Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop
        return $true
    } catch {
        try {
            Get-ChildItem -LiteralPath $Path -Recurse -Force -ErrorAction SilentlyContinue |
                ForEach-Object { try { $_.Attributes = [IO.FileAttributes]::Normal } catch {} }
            Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop
            return $true
        } catch {
            Write-Host "[uninstall] could not remove $Path" -ForegroundColor Red
            Write-Host "            $($_.Exception.Message)" -ForegroundColor Red
            return $false
        }
    }
}

$Purge = $false
foreach ($arg in $args) {
    switch ($arg) {
        "--purge" { $Purge = $true }
        "-Purge"  { $Purge = $true }
        default {
            if ($arg -in @("-h", "--help", "-Help")) {
                Write-Host "Usage: .\uninstall.ps1 [--purge]"
                Write-Host "  --purge   also remove the SWE-bench\ clone and evomas\.env + api\.env (secrets!)"
                exit 0
            }
            Write-Host "[uninstall] unknown arg: $arg (try --help)" -ForegroundColor Red
            exit 2
        }
    }
}

# --- 1. Unregister the Jupyter kernel (before we delete the venv) ------------
# The kernelspec lives under the user's Jupyter data dir, not inside the venv,
# so remove it explicitly while the venv's python still exists. Guarded in a
# try/catch because the venv may not have jupyter (partial/broken install): with
# $ErrorActionPreference = "Stop", the native command's stderr routed through
# `2>&1` would otherwise surface as a terminating NativeCommandError and abort
# the whole uninstall. Missing kernel/jupyter is a no-op, not a failure.
if (Test-Path $PythonEvomas) {
    Write-Host "[uninstall] removing 'evomas' Jupyter kernel" -ForegroundColor Cyan
    try {
        & $PythonEvomas -m jupyter kernelspec remove -f evomas 2>&1 | Out-Null
    } catch {
        Write-Host "[uninstall] (kernel not registered or jupyter unavailable -- skipping)" -ForegroundColor Cyan
    }
}

# --- 2. Strip the evomas function block from the PowerShell profile ----------
# Same regex install.ps1 uses to refresh the block, applied here to delete it.
$ProfilePath = $PROFILE
if (Test-Path $ProfilePath) {
    $existing = Get-Content $ProfilePath -Raw -ErrorAction SilentlyContinue
    if ($existing -and $existing.Contains($Marker)) {
        Write-Host "[uninstall] removing evomas function from $ProfilePath" -ForegroundColor Cyan
        $pattern = "(?ms)" + [regex]::Escape($Marker) + ".*?" + [regex]::Escape($EndMarker)
        $existing = [regex]::Replace($existing, $pattern, "").TrimEnd()
        if ($existing) { $existing += "`r`n" }
        # Guarded: a locked/read-only profile would otherwise throw under
        # $ErrorActionPreference = "Stop" and skip the venv removal below.
        try {
            Set-Content -Path $ProfilePath -Value $existing -Encoding utf8 -ErrorAction Stop
        } catch {
            Write-Host "[uninstall] could not rewrite $ProfilePath -- remove the evomas function block by hand." -ForegroundColor Yellow
        }
    }
}

# --- 3. Remove app\node_modules (regenerated by install.ps1's npm install) ---
$NodeModules = Join-Path $RepoRoot "app\node_modules"
if (Test-Path $NodeModules) {
    Write-Host "[uninstall] removing app\node_modules" -ForegroundColor Cyan
    [void](Remove-Tree $NodeModules)
}

# --- 4. Remove the venv ------------------------------------------------------
if (Test-Path $VenvDir) {
    Write-Host "[uninstall] removing venv at $VenvDir" -ForegroundColor Cyan
    if (-not (Remove-Tree $VenvDir)) {
        Write-Host "[uninstall] the venv is still in use. Close anything running its Python --" -ForegroundColor Yellow
        Write-Host "            a VSCode/Jupyter 'Python 3 (EvoMas)' kernel, a running 'evomas api'," -ForegroundColor Yellow
        Write-Host "            or an activated venv shell -- then re-run .\uninstall.ps1." -ForegroundColor Yellow
    }
} else {
    Write-Host "[uninstall] no venv at $VenvDir (already gone)" -ForegroundColor Cyan
}

# --- 5. --purge extras (SWE-bench clone + .env secrets) ----------------------
if ($Purge) {
    $SwebenchDir = Join-Path $RepoRoot "SWE-bench"
    if (Test-Path $SwebenchDir) {
        Write-Host "[uninstall] --purge: removing SWE-bench clone at $SwebenchDir" -ForegroundColor Yellow
        try {
            Remove-Item -Recurse -Force $SwebenchDir -ErrorAction Stop
        } catch {
            # A WSL-built harness venv contains symlinks into the Linux
            # filesystem that Windows can't delete. Fall back to WSL.
            Write-Host "[uninstall] Windows couldn't remove it (likely WSL symlinks in venv/)." -ForegroundColor Yellow
            Write-Host "            Remove it from WSL: wsl -- rm -rf '$($SwebenchDir -replace '\\','/')'"
        }
    }
    foreach ($envFile in @((Join-Path $RepoRoot "evomas\.env"), (Join-Path $RepoRoot "api\.env"))) {
        if (Test-Path $envFile) {
            Write-Host "[uninstall] --purge: removing $envFile (held your secrets)" -ForegroundColor Yellow
            try {
                Remove-Item -Force $envFile -ErrorAction Stop
            } catch {
                Write-Host "[uninstall] could not remove $envFile ($($_.Exception.Message)) -- delete it by hand." -ForegroundColor Yellow
            }
        }
    }
} else {
    Write-Host "[uninstall] kept SWE-bench\ and the .env files -- pass --purge to remove them too." -ForegroundColor Cyan
}

Write-Host ""
Write-Host "[uninstall] done. Open a fresh PowerShell window so the removed evomas" -ForegroundColor Green
Write-Host "            function clears from your current session."
