#!/usr/bin/env bash
# Reverse of install.sh (Linux / macOS / WSL). Removes the artefacts install.sh
# creates: the ~/.evomas-venv, the `evomas` function in your shell rc, the
# 'evomas' Jupyter kernel, and app/node_modules. Your data is left alone by
# default -- pass --purge to ALSO delete the SWE-bench clone and the .env files
# (which hold your API keys). Idempotent: safe to re-run, no-ops on anything
# already gone.
set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# Same path install.sh / start_api.sh / run_tests.py use.
VENV_DIR="$HOME/.evomas-venv"
PYTHON_EVOMAS="$VENV_DIR/bin/python"

# Markers install.sh wraps its rc function in (kept in sync with install.sh).
MARKER="# >>> evomas-cli >>>"
END_MARKER="# <<< evomas-cli <<<"

PURGE=0
for arg in "$@"; do
    case "$arg" in
        --purge) PURGE=1 ;;
        -h|--help)
            echo "Usage: bash uninstall.sh [--purge]"
            echo "  --purge   also remove the SWE-bench/ clone and evomas/.env + api/.env (secrets!)"
            exit 0 ;;
        *) echo "[uninstall] unknown arg: $arg (try --help)" >&2; exit 2 ;;
    esac
done

# ── 1. Unregister the Jupyter kernel (before we delete the venv) ──────────────
# The kernelspec lives under the user's Jupyter data dir, not inside the venv,
# so it must be removed explicitly. Use the venv's python while it still exists;
# fall back to any jupyter on PATH.
if [ -x "$PYTHON_EVOMAS" ]; then
    echo "[uninstall] removing 'evomas' Jupyter kernel"
    "$PYTHON_EVOMAS" -m jupyter kernelspec remove -f evomas >/dev/null 2>&1 || \
        echo "[uninstall] (kernel not registered or jupyter unavailable -- skipping)"
elif command -v jupyter >/dev/null 2>&1; then
    echo "[uninstall] removing 'evomas' Jupyter kernel"
    jupyter kernelspec remove -f evomas >/dev/null 2>&1 || true
fi

# ── 2. Strip the evomas function block from every shell rc that carries it ────
# install.sh only ever writes to the current shell's rc, but a user may have
# run it under more than one shell -- clean them all. The awk pass mirrors the
# robust marker-strip install.sh uses (preserves any text on the marker lines).
strip_rc() {
    local rc="$1"
    [ -f "$rc" ] || return 0
    grep -qF "$MARKER" "$rc" || return 0
    echo "[uninstall] removing evomas function from $rc"
    awk -v s="$MARKER" -v e="$END_MARKER" '
        BEGIN { skip = 0 }
        {
            spos = index($0, s)
            if (spos > 0) {
                if (!skip && spos > 1) print substr($0, 1, spos - 1)
                skip = 1
                next
            }
            if (skip) {
                epos = index($0, e)
                if (epos > 0) {
                    skip = 0
                    rest = substr($0, epos + length(e))
                    if (rest != "") print rest
                }
                next
            }
            print
        }
    ' "$rc" > "$rc.tmp" && mv "$rc.tmp" "$rc"
}
for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.bash_profile" \
          "$HOME/.config/fish/config.fish" "$HOME/.profile"; do
    strip_rc "$rc"
done

# ── 3. Remove app/node_modules (regenerated by install.sh's npm install) ──────
if [ -d "$REPO_ROOT/app/node_modules" ]; then
    echo "[uninstall] removing app/node_modules"
    rm -rf "$REPO_ROOT/app/node_modules"
fi

# ── 4. Remove the venv ────────────────────────────────────────────────────────
if [ -d "$VENV_DIR" ]; then
    echo "[uninstall] removing venv at $VENV_DIR"
    rm -rf "$VENV_DIR"
else
    echo "[uninstall] no venv at $VENV_DIR (already gone)"
fi

# ── 5. --purge extras (SWE-bench clone + .env secrets) ────────────────────────
if [ "$PURGE" = 1 ]; then
    if [ -d "$REPO_ROOT/SWE-bench" ]; then
        echo "[uninstall] --purge: removing SWE-bench clone at $REPO_ROOT/SWE-bench"
        rm -rf "$REPO_ROOT/SWE-bench"
    fi
    for env_file in "$REPO_ROOT/evomas/.env" "$REPO_ROOT/api/.env"; do
        if [ -f "$env_file" ]; then
            echo "[uninstall] --purge: removing $env_file (held your secrets)"
            rm -f "$env_file"
        fi
    done
else
    echo "[uninstall] kept SWE-bench/ and the .env files -- pass --purge to remove them too."
fi

echo
echo "[uninstall] done. Open a new shell (or re-source your rc) so the removed"
echo "            evomas function clears from your current session."
