# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import app.src.agents.repo_scanner_agent as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    repo_scanner_agent_0 = module_0.RepoScannerAgent()
    assert (
        f"{type(repo_scanner_agent_0.model).__module__}.{type(repo_scanner_agent_0.model).__qualname__}"
        == "src.models.ollama_model.OllamaWrapper"
    )
    assert repo_scanner_agent_0.max_depth == 5
    assert repo_scanner_agent_0.max_file_bytes == 1000000
    assert module_0.RepoScannerAgent.EXCLUDED_DIRS == {
        ".venv",
        "dist",
        "venv",
        "build",
        ".mypy_cache",
        "node_modules",
        ".git",
        ".pytest_cache",
        "env",
        "venv_win",
        "venv_wsl",
        "__pycache__",
    }
    assert module_0.RepoScannerAgent.EXCLUDED_EXTS == {".lock", ".log", ".pyc", ".pyo"}
    assert module_0.RepoScannerAgent.INCLUDED_EXTS == {
        ".hpp",
        ".rb",
        ".scala",
        ".json",
        ".md",
        ".tsx",
        ".h",
        ".ps1",
        ".ts",
        ".sh",
        ".xml",
        ".yml",
        ".css",
        ".kt",
        ".kts",
        ".cs",
        ".c",
        ".txt",
        ".swift",
        ".sql",
        ".go",
        ".yaml",
        ".js",
        ".php",
        ".py",
        ".cpp",
        ".html",
        ".toml",
        ".java",
    }
    repo_scanner_agent_0.run(repo_scanner_agent_0)


def test_case_1():
    repo_scanner_agent_0 = module_0.RepoScannerAgent()
    assert (
        f"{type(repo_scanner_agent_0.model).__module__}.{type(repo_scanner_agent_0.model).__qualname__}"
        == "src.models.ollama_model.OllamaWrapper"
    )
    assert repo_scanner_agent_0.max_depth == 5
    assert repo_scanner_agent_0.max_file_bytes == 1000000
    assert module_0.RepoScannerAgent.EXCLUDED_DIRS == {
        ".venv",
        "dist",
        "venv",
        "build",
        ".mypy_cache",
        "node_modules",
        ".git",
        ".pytest_cache",
        "env",
        "venv_win",
        "venv_wsl",
        "__pycache__",
    }
    assert module_0.RepoScannerAgent.EXCLUDED_EXTS == {".lock", ".log", ".pyc", ".pyo"}
    assert module_0.RepoScannerAgent.INCLUDED_EXTS == {
        ".hpp",
        ".rb",
        ".scala",
        ".json",
        ".md",
        ".tsx",
        ".h",
        ".ps1",
        ".ts",
        ".sh",
        ".xml",
        ".yml",
        ".css",
        ".kt",
        ".kts",
        ".cs",
        ".c",
        ".txt",
        ".swift",
        ".sql",
        ".go",
        ".yaml",
        ".js",
        ".php",
        ".py",
        ".cpp",
        ".html",
        ".toml",
        ".java",
    }
