# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import app.src.utils.json as module_0


def test_case_0():
    module_0.get_nodes_data()


def test_case_1():
    module_0.get_nodes_data()
