# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import app.src.agents.bug_detector_agent as module_0


def test_case_0():
    bug_detector_agent_0 = module_0.BugDetectorAgent()
    assert module_0.BugDetectorAgent.SUPPORTED_SOURCE_EXTS == (
        ".py",
        ".js",
        ".ts",
        ".tsx",
        ".java",
        ".cpp",
        ".c",
        ".h",
        ".hpp",
        ".cs",
        ".go",
        ".rb",
        ".php",
        ".swift",
        ".kt",
        ".kts",
        ".scala",
        ".sql",
    )
    assert module_0.BugDetectorAgent.KEYWORDS == [
        "TODO",
        "FIXME",
        "NotImplementedError",
        "pass  #",
        "except Exception",
        "except:",
        "raise ",
        "assert False",
        "eval(",
        "exec(",
        "KeyError",
        "IndexError",
    ]
    dict_0 = {bug_detector_agent_0: bug_detector_agent_0}
    bug_detector_agent_0.run(dict_0)
