# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import app.src.agents.validator_agent as module_0


def test_case_0():
    dict_0 = {}
    validator_agent_0 = module_0.ValidatorAgent()
    validator_agent_0.run(dict_0)
