# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import app.src.tests.workflow_test as module_0


def test_case_0():
    a_p_r_state_0 = module_0.APRState()
    str_0 = module_0.should_continue(a_p_r_state_0)
    assert str_0 == "end"


@pytest.mark.xfail(strict=True)
def test_case_1():
    a_p_r_state_0 = module_0.APRState()
    str_0 = module_0.should_continue(a_p_r_state_0)
    assert str_0 == "end"
    module_0.analyze_node(a_p_r_state_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    module_0.build_workflow()
