# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import app.src.agents.base_agent as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    base_agent_0.extract_json(base_agent_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    dict_0 = {
        base_agent_0: base_agent_0,
        base_agent_0: base_agent_0,
        base_agent_0: base_agent_0,
    }
    base_agent_0.build_messages(dict_0, base_agent_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "fmoh"
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    base_agent_0.build_messages(base_agent_0, str_0, include_state_keys=str_0)


def test_case_3():
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    str_0 = ""
    base_agent_0.extract_json(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = " x"
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    base_agent_0.extract_json(str_0)
    base_agent_0.build_messages(base_agent_0, str_0, include_state_keys=str_0)


def test_case_5():
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    str_0 = "+"
    base_agent_0.extract_json(str_0)


def test_case_6():
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    str_0 = "^ NIN"
    base_agent_0.extract_json(str_0)


def test_case_7():
    str_0 = "\\u<"
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    dict_0 = {}
    base_agent_0.build_messages(dict_0, str_0)
    base_agent_0.extract_json(str_0)


def test_case_8():
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    str_0 = "I3[7Usi"
    base_agent_0.extract_json(str_0)


def test_case_9():
    base_agent_0 = module_0.BaseAgent()
    assert (
        module_0.BaseAgent.TASK_SYSTEM_PROMPT
        == "You are fixing bugs in a repository using automated program repair."
    )
    base_agent_1 = module_0.BaseAgent()
    base_agent_2 = module_0.BaseAgent()
    base_agent_3 = module_0.BaseAgent()
    str_0 = " MCs"
    str_1 = "?\x0cS}Cw]\\7gk'\x0c]R"
    base_agent_4 = module_0.BaseAgent()
    str_2 = "6|4%K@_sVX4lj\nJf~r^"
    base_agent_5 = module_0.BaseAgent()
    var_0 = base_agent_2.extract_json(str_1)
    dict_0 = {
        base_agent_0: base_agent_1,
        str_2: base_agent_4,
        base_agent_3: base_agent_3,
        base_agent_4: base_agent_3,
        str_2: str_1,
        base_agent_1: str_0,
        base_agent_3: base_agent_3,
        base_agent_3: base_agent_3,
        var_0: base_agent_4,
        str_2: base_agent_3,
        str_0: base_agent_1,
        base_agent_5: base_agent_0,
        str_1: str_0,
        base_agent_2: base_agent_3,
        base_agent_1: str_2,
        str_1: base_agent_2,
        str_0: str_0,
        base_agent_4: base_agent_0,
        str_0: base_agent_3,
        base_agent_1: base_agent_1,
        base_agent_2: base_agent_2,
    }
    dict_1 = {
        str_1: base_agent_3,
        base_agent_3: str_0,
        base_agent_1: dict_0,
        str_0: dict_0,
        base_agent_5: str_0,
        str_2: str_0,
        var_0: str_0,
        base_agent_2: str_0,
        var_0: dict_0,
        base_agent_0: str_0,
        base_agent_3: base_agent_3,
    }
    dict_2 = {
        base_agent_0: base_agent_1,
        base_agent_3: base_agent_1,
        base_agent_3: str_1,
        base_agent_1: dict_1,
        base_agent_0: base_agent_2,
        base_agent_5: str_0,
        var_0: dict_0,
        base_agent_2: dict_1,
        str_0: base_agent_3,
        var_0: base_agent_3,
        str_1: base_agent_5,
        var_0: dict_1,
    }
    base_agent_5.build_messages(dict_2, str_1)
