# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import app.src.tools.tool_registry as module_0


def test_case_0():
    module_0.get_ollama_tools()
